sudo: required
dist: trusty
language: java
jdk:
- openjdk8


addons:
  sonarcloud:
    organization: "esposito-matteo190320202155"
    token: 5d81831e177714659ddbf9942f258211923e9bee

cache:
  directories:
  - $HOME/.m2
  - $HOME/local

git:
  depth: 150


install: mvn clean install -q -DfailIfNoTests=false -Dhadoop.version=2.7.1 -Dlicense.skip  -Drat.skip=true -Drat.numUnapprovedLicenses=100000
script: mvn clean verify -Drat.skip=true  -Drat.numUnapprovedLicenses=10000000 -Pcoverage

