language: java
jdk:
- openjdk8


addons:
  sonarcloud:
    organization: "esposito-matteo190320202155"
    token: e4d3d8da48c1d809f55cb671dbfdf67bbd459d66
    
install:
- mvn verify -DfailIfNoTests=false -Dmaven.test.failure.ignore=true sonar:sonar -Dsonar.projectKey=Esposito-Matteo_tajo 
 
