sudo: required
dist: trusty
language: java
jdk:
- openjdk8


addons:
  sonarcloud:
    organization: "esposito-matteo190320202155"
    token:
      secure: e4d3d8da48c1d809f55cb671dbfdf67bbd459d66
    
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report sonar:sonar -Dsonar.projectKey=Esposito-Matteo_tajo
#- if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]; then mvn sonar:sonar; fi
