sudo: required
dist: trusty
language: java
jdk:
- openjdk8


addons:
  sonarcloud:
    organization: "esposito-matteo190320202155"
    token: 5d81831e177714659ddbf9942f258211923e9bee
    
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package org.jacoco:jacoco-maven-plugin:report
- if [ "$JAVA_HOME" = "/usr/lib/jvm/java-1.8.0-openjdk-amd64" ]; then mvn sonar:sonar; fi
